export const planetData = {
  "data": [
    {
      "Planet": "MERCURY",
      "Mass": "0.33 (10^24kg)",
      "Diameter": (4879),
      "Density": "5427 (kg/m3)",
      "Gravity": "3.7 (m/s2)",
      "Escape Velocity": 4.3,
      "Rotation Period": "1407.6 (hours)",
      "Length of Day": "4222.6 (hours)",
      "Distance from Sun": 57.9,
      "Perihelion": "46.0 (10^6 km)",
      "Aphelion": "69.8 (10^6 km)",
      "Orbital Period": "88.0 (days)",
      "Orbital Velocity": "47.4 (km/s)",
      "Orbital Inclination": "7.0 (degrees)",
      "Orbital Eccentricity": "0.205",
      "Obliquity to Orbit": 0.034,
      "Mean Temperature": "167 (C)",
      "Surface Pressure": "0 (bars)",
      "Number of Moons": "0",
      "Ring System?": "No",
      "Global Magnetic Field?": "Yes"
    },

    {
      "Planet": "VENUS",
      "Mass": "4.87 (10^24kg)",
      "Diameter": (12104),
      "Density": "5243 (kg/m3)",
      "Gravity": "8.9 (m/s2)",
      "Escape Velocity": 10.4,
      "Rotation Period": "-5832.5 (hours)",
      "Length of Day": "2802.0 (hours)",
      "Distance from Sun": 108.2,
      "Perihelion": "107.5 (10^6 km)",
      "Aphelion": "108.9 (10^6 km)",
      "Orbital Period": "224.7 (days)",
      "Orbital Velocity": "35.0 (km/s)",
      "Orbital Inclination": "3.4 (degrees)",
      "Orbital Eccentricity": "0.007",
      "Obliquity to Orbit": 177.4,
      "Mean Temperature": "464 (C)",
      "Surface Pressure": "92 (bars)",
      "Number of Moons": "0",
      "Ring System?": "No",
      "Global Magnetic Field?": "No"
    },

    {
      "Planet": "EARTH",
      "Mass": "5.97 (10^24kg)",
      "Diameter": (12756),
      "Density": "5514 (kg/m3)",
      "Gravity": "9.8 (m/s2)",
      "Escape Velocity": 11.2,
      "Rotation Period": "23.9 (hours)",
      "Length of Day": "24.0 (hours)",
      "Distance from Sun": 149.6,
      "Perihelion": "147.1 (10^6 km)",
      "Aphelion": "152.1 (10^6 km)",
      "Orbital Period": "365.2 (days)",
      "Orbital Velocity": "29.8 (km/s)",
      "Orbital Inclination": "0.0 (degrees)",
      "Orbital Eccentricity": "0.017",
      "Obliquity to Orbit": 23.4,
      "Mean Temperature": "15 (C)",
      "Surface Pressure": "1 (bars)",
      "Number of Moons": "1",
      "Ring System?": "No",
      "Global Magnetic Field?": "Yes"
    },

    {
      "Planet": "MARS",
      "Mass": "0.642 (10^24kg)",
      "Diameter": (6792),
      "Density": "3933 (kg/m3)",
      "Gravity": "3.7 (m/s2)",
      "Escape Velocity": 5.0,
      "Rotation Period": "24.6 (hours)",
      "Length of Day": "24.7 (hours)",
      "Distance from Sun": 227.9,
      "Perihelion": "206.6 (10^6 km)",
      "Aphelion": "249.2 (10^6 km)",
      "Orbital Period": "687.0 (days)",
      "Orbital Velocity": "24.1 (km/s)",
      "Orbital Inclination": "1.9 (degrees)",
      "Orbital Eccentricity": "0.094",
      "Obliquity to Orbit": 25.2,
      "Mean Temperature": "-65 (C)",
      "Surface Pressure": "0.01 (bars)",
      "Number of Moons": "2",
      "Ring System?": "No",
      "Global Magnetic Field?": "No"
    },

    {
      "Planet": "JUPITER",
      "Mass": "1898 (10^24kg)",
      "Diameter": (142984),
      "Density": "1326 (kg/m3)",
      "Gravity": "23.1 (m/s2)",
      "Escape Velocity": 59.5,
      "Rotation Period": "9.9 (hours)",
      "Length of Day": "9.9 (hours)",
      "Distance from Sun": 778.6,
      "Perihelion": "740.5 (10^6 km)",
      "Aphelion": "816.6 (10^6 km)",
      "Orbital Period": "4331 (days)",
      "Orbital Velocity": "13.1 (km/s)",
      "Orbital Inclination": "1.3 (degrees)",
      "Orbital Eccentricity": "0.049",
      "Obliquity to Orbit": 3.1,
      "Mean Temperature": "-110 (C)",
      "Surface Pressure": "Unknown (bars)",
      "Number of Moons": "79",
      "Ring System?": "Yes",
      "Global Magnetic Field?": "Yes"
    },

    {
      "Planet": "SATURN",
      "Mass": "568 (10^24kg)",
      "Diameter": (120536),
      "Density": "687 (kg/m3)",
      "Gravity": "9.0 (m/s2)",
      "Escape Velocity": 35.5,
      "Rotation Period": "10.7 (hours)",
      "Length of Day": "10.7 (hours)",
      "Distance from Sun": 1433.5,
      "Perihelion": "1352.6 (10^6 km)",
      "Aphelion": "1514.5 (10^6 km)",
      "Orbital Period": "10747 (days)",
      "Orbital Velocity": "9.7 (km/s)",
      "Orbital Inclination": "2.5 (degrees)",
      "Orbital Eccentricity": "0.057",
      "Obliquity to Orbit": 26.7,
      "Mean Temperature": "-140 (C)",
      "Surface Pressure": "Unknown (bars)",
      "Number of Moons": "82",
      "Ring System?": "Yes",
      "Global Magnetic Field?": "Yes"
    },

    {
      "Planet": "URANUS",
      "Mass": "86.8 (10^24kg)",
      "Diameter": (51118),
      "Density": "1271 (kg/m3)",
      "Gravity": "8.7 (m/s2)",
      "Escape Velocity": 21.3,
      "Rotation Period": "-17.2 (hours)",
      "Length of Day": "17.2 (hours)",
      "Distance from Sun": 2872.5,
      "Perihelion": "2741.3 (10^6 km)",
      "Aphelion": "3003.6 (10^6 km)",
      "Orbital Period": "30589 (days)",
      "Orbital Velocity": "6.8 (km/s)",
      "Orbital Inclination": "0.8 (degrees)",
      "Orbital Eccentricity": "0.046",
      "Obliquity to Orbit": 97.8,
      "Mean Temperature": "-195 (C)",
      "Surface Pressure": "Unknown (bars)",
      "Number of Moons": "27",
      "Ring System?": "Yes",
      "Global Magnetic Field?": "Yes"
    },

    {
      "Planet": "NEPTUNE",
      "Mass": "102 (10^24kg)",
      "Diameter": (49528),
      "Density": "1638 (kg/m3)",
      "Gravity": "11.0 (m/s2)",
      "Escape Velocity": 23.5,
      "Rotation Period": "16.1 (hours)",
      "Length of Day": "16.1 (hours)",
      "Distance from Sun": 4495.1,
      "Perihelion": "4444.5 (10^6 km)",
      "Aphelion": "4545.7 (10^6 km)",
      "Orbital Period": "59800 (days)",
      "Orbital Velocity": "5.4 (km/s)",
      "Orbital Inclination": "1.8 (degrees)",
      "Orbital Eccentricity": "0.011",
      "Obliquity to Orbit": 28.3,
      "Mean Temperature": "-200 (C)",
      "Surface Pressure": "Unknown (bars)",
      "Number of Moons": "14",
      "Ring System?": "Yes",
      "Global Magnetic Field?": "Yes"
    },
  ]
}